sonar.projectKey=mohamedyasssine_wefund-dashboard-si
sonar.organization=mohamedyasssine
sonar.projectName=wefund-dashboard-si

sonar.sources=app,components,context,domain,lib,types
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.ts,__tests__/**/*.test.tsx

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=.next/**,node_modules/**,coverage/**,public/**
